<?php

declare(strict_types=1);

/**
 * @file
 * Provides a company entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function company_theme(): array {
  return [
    'company' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for company templates.
 *
 * Default template: company.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the company information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_company(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function company_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish companies.
      $storage = \Drupal::entityTypeManager()->getStorage('company');
      $company_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($company_ids) as $company) {
        $company->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize companies.
      $storage = \Drupal::entityTypeManager()->getStorage('company');
      $company_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($company_ids) as $company) {
        $company->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function company_user_predelete(UserInterface $account): void {
  // Delete companies that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('company');
  $company_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($company_ids)
  );
}
